language: python

python:
  - "3.7"

install:
  - pip install -U pip
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
  - pip install codecov
  - python setup.py build_ext --inplace
  - python setup.py install

  jobs:
    include:
        - stage: test
          name: test
          script: pytest -sv tests --cov kaggler

after_success:
    - codecov
